env:
  browser: true
  es6: true
extends:
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  object-curly-newline: off
  arrow-parens:
    - error
    - as-needed
    - requireForBlockBody: false
  no-param-reassign:
    - error
    - props: false
  no-underscore-dangle: off
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
  react/prop-types: off
  react/jsx-props-no-spreading:
    - error
    - html: enforce
      custom: ignore
      explicitSpread: ignore
  react/jsx-curly-spacing:
    - error
    - when: always
  react/forbid-prop-types: off